### ISSUE TITLE
snippets: review and update snippets

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#160]
See https://github.com/microsoft/vscode-go/issues/2380 for the original discussion.

**Comment by hyangah** [comment]
Facts to consider (from https://github.com/microsoft/vscode-go/issues/2380#issuecomment-622009130)

* Due to the current limitation in VS Code's snippets, it's hard to selectively disable snippets included in an extension. 
* The snippets may interfere with the language servers' auto-completion features. Be conservative in accepting any new snippet contribution.
* There is clear overlap with some autocompletion features language servers can provide. So, if `gopls` can provide a better option, do not add the snippet.
* Encourage to use personal snippets https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets instead of adding to the extension's snippet unless the snippet promotes commonly used idiomatic pattern.

Existing snippets 

Μaybe

- [ ] single import: `im` -> `import "package"`
- [ ] multiple imports: `ims` -> `import ( "package" )`
- [ ] single constant: `co` -> `const name = value` 
- [ ] multiple constants: `cos` -> `const ( name = value )`
- [ ] type interface declaration: `tyi` -> `type name interface { }`
- [ ] type struct declaration: `tys` -> `type name struct { }`
- [ ] package main and main function: `pkgm` -> `package main\n\nfunc main() { }`
- [ ] function declaration: `func` -> `func $1($2) $3 { $0 }`
- [ ] variable declaration: `var` -> `var $1 $2`
- [ ] switch statement: `switch` -> `switch $1 { case $2: }`
- [ ] select statement: `sel` -> `select { case $1: }`
- [ ] case clause: `cs` -> `case $1:`
- [ ] for statement: `for` -> `for i := 0; i < count; i++ { }`
- [ ] for range statement: `forr` -> `for _, var := range var { }`
- [ ] channel declaration: `ch` -> `chan type`
- [ ] map declaration: `map` -> `map[type]type`
- [ ] empty interface: `in` -> `interface{}`
- [ ] if statement: `if` -> `if condition { }`
- [ ] else branch: `el` -> `else { }`
- [ ] if else statement: `ie` -> `if condition { } else { }`
- [ ] if err != nil: `iferr` -> `if err != nil { return nil, err }`
- [ ] goroutine anonymous function: `go` -> `go func() { }( )`
- [ ] goroutine function: `gf` -> `go $1($0)`
- [ ] defer statement: `df` -> `defer $1($0)`

Can gopls's completion do a reasonable job if not better?

- [ ] fmt.Println: `fp` -> `fmt.Println("$1")`
- [ ] fmt.Printf: `ff` -> `fmt.Printf("$1", $2)`
- [ ] log.Println: `lp` -> `log.Println("$1")`
- [ ] log.Printf: `lf` -> `log.Printf("$1", $2)`
- [ ] log variable content: `lv` -> `log.Printf("$1: %#+v\n", $1)`
- [ ] t.Logf: `tl` -> `t.Log("$1")`
- [ ] t.Logf: `tlf` -> `t.Logf("$1", $2)`
- [ ] t.Logf variable content: `tlv` -> `t.Logf("$1: %#+v\n", $1)`
- [ ] make(...): `make` -> `make($1, $2)`
- [ ] new(...): `new` -> `new($1)`
- [ ] panic(...): `pn` -> `panic("")`
- [ ] method declaration: `meth` ->`func (${1:receiver} ${2:type}) ${3:method}($4) $5 {\n\t$0\n}`

HTTP specific shortcut keys, maybe reject?

- [ ] http ResponseWriter *Request: `wr` -> `w http.ResponseWriter, r *http.Request`,
- [ ] http.HandleFunc: `hf` -> `http.HandlerFunc("/", handler)`
- [ ] http handler declaration: `hand` -> `func (w http.ResponseWriter, r *http.Request) { }`
- [ ] http.Redirect: `rd` -> `http.Redirect(w, r, "/", https.StatusFound)`
- [ ] http.Error: `herr` -> `http.Error(w, err.Error(), http.StatusInternalServerError)`
- [ ] http.ListenAndServe: `las` ->`http.ListenAdnServe(":8080", nil)`
- [ ] http.Serve: `sv` -> `http.Serve(":8080", nil)`

Test specific templates, maybe?

- [ ] test function: `tf` -> `func Test$1(t *testing.T) {}"`
- [ ] benchmark function: `bf` -> `func Benchmark$1(b *testing.B) { for i := 0; i < b.N; i++ { } }`
- [ ] example function: `ef` -> `func Example$1() {\n\t$2\n\t//Output:\n\t$3\n}`
- [ ] table driven test: `tdt` -> `func Test$1(t *testing.T) {\n\ttestCases := []struct {\n\t\tdesc\tstring\n\t\t$2\n\t}{\n\t\t{\n\t\t\tdesc: \"$3\",\n\t\t\t$4\n\t\t},\n\t}\n\tfor _, tC := range testCases {\n\t\tt.Run(tC.desc, func(t *testing.T) {\n\t\t\t$0\n\t\t})\n\t}\n}`
- [ ] init function: `finit` -> `func init() { }`
- [ ] main function: `fmain` -> `func main() { }`

To delete

- [ ] hello world web app: `helloweb` ->`package main\n\nimport (\n\t\"fmt\"\n\t\"net/http\"\n\t\"time\"\n)\n\nfunc greet(w http.ResponseWriter, r *http.Request) {\n\tfmt.Fprintf(w, \"Hello World! %s\", time.Now())\n}\n\nfunc main() {\n\thttp.HandleFunc(\"/\", greet)\n\thttp.ListenAndServe(\":8080\", nil)\n}`
- [ ] sort implementation: `sort` -> `type ${1:SortBy} []${2:Type}\n\nfunc (a $1) Len() int           { return len(a) }\nfunc (a $1) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }\nfunc (a $1) Less(i, j int) bool { ${3:return a[i] < a[j]} }`
   : recent versions of Go have better APIs than this (`sort.Sort`, ...)

New things to consider

- [ ] Add struct and struct field snippets (microsoft/vscode-go#2867)
- [ ] Snippets: GoRoutine Function removal (microsoft/vscode-go#2717)
- [ ] added snippets for friendly failing test output (microsoft/vscode-go#2616)
- [ ] snippets: add friendly failing test output snippet (microsoft/vscode-go#2615)
- [ ] Test snippet should support Parallel execution by default (microsoft/vscode-go#2291)
- [ ] Contributing to snippets: mutex lock and unlock support (microsoft/vscode-go#2273)
- [ ] Snippet for TestMain (https://github.com/golang/vscode-go/pull/629)
