### ISSUE TITLE
Testing API followup

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#1641]
There are a variety of features I want to implement and changes I want to make, following the completion of the initial test controller implementation, #1579. Instead of opening a bunch of issues, I'm going to list my thoughts here, so the team can decide what does and does not merit an issue.

* [ ] **Refactoring** - #1702 - consolidate testing, refactor prior test infrastructure (prior to [CL 330809](https://go-review.googlesource.com/q/I027c7c3b615eda4c528da9739520e6bfd1aa6911)) to be a layer on top of `runTests`.
* [x] **Settings** - respect `files.exclude` etc - #1739 - [CL](https://go-review.googlesource.com/c/vscode-go/+/351172)
* [x] **Subtests** - Make subtests runnable - [CL](https://go-review.googlesource.com/q/I26eac8a5a396df3923073274ed93d9c59107d9c3)
* [x] **Subtests** - Discover subtests programatically<sup>1</sup> #1602
* [ ] **Build tags** - Improve handling of build-tag-specific tests: #1673
* [x] **Build tags** - Testing API tag support: https://github.com/microsoft/vscode/issues/129456
* [x] **Profiling** - I want to run a test using the profiler to collect CPU and/or Memory data #1685
* [x] **Profiling** - I want to see the results for the profiler in a graphical way - [CL](https://go-review.googlesource.com/c/vscode-go/+/345477)
* [x] **Profiling** - The same for all the tests/benchmarks in a package
* [ ] **Profiling** - I want to be able to compare two profiler results
* [ ] **Profiling** - Retain profiles across VSCode sessions - that is, don't store profiles in a session-specific temp directory
* [x] **Test suites** - Add support for test suites such as `github.com/stretchr/testify/suite` - [CL](https://go-review.googlesource.com/c/vscode-go/+/343489)

### Test Output

`go test` outputs events. Those events are (hopefully) attached to a specific test, but otherwise have no structure.

* Determining what file and line the output comes from
  * I attach output to a given `file:line` by looking for `file.go:123: ...`. This is less than ideal, but I think it's about all we *can* do
* Differentiating between errors and generic log messages
  * `go test` does not have any notion of error messages, so this has to be heuristic
  * I was using logic I stole from my extension to recognize when output is an error message from `stretchr/testify`
  * https://github.com/microsoft/vscode/issues/129201

### Sub-tests

**statue: done**

Currently, I discover sub tests by analyzing the test output. If I see a test event where the `Test` field is `TestFoo/Bar`, I create `Bar` as a sub-test of `TestFoo`.

* If a file is edited and the edit range overlaps a test, I delete all sub-tests of that test.
  * Given that sufficiently compelx/obfuscated sub-tests will not be semantically recognizable<sup>1</sup>, I don't see a way around this.
  * If I don't do this, edits to a test with semantically unrecognizable sub-tests will result in stale sub-test definitions, which IMO is a worse UX.
* When a test is run, I delete all dynamically discovered sub-tests of that test.

<sup>1</sup> There will always be sub-tests that cannot be identified without resorting to code execution of some sort. Sufficiently complex/obfuscated code will defeat any attempt to identify 1) locations where `(*testing.T).Run` is called, 2) whether and how many times the call occurred, and 3) the name passed to each call.<br />

### Debugging

**status: done** for a single test

#1590 does not support debugging tests. Debugging a test is very different than running a test, in that tests are run by spawning `go test` as a Node child process, whereas tests are debugged by starting a VSCode debugging session. Proper support for debugging tests with a test controller would require updating the test state (running, failed, passed, etc), would require getting output from the debug session. I opted not to add all this complexity to the already rather large initial implementation.

**Comment by firelizzard18** [comment]
@hyangah @suzmue, Do you have an op

**Comment by firelizzard18** [comment]
Wrong button...

**Comment by firelizzard18** [comment]
[CL 345470](https://go-review.googlesource.com/c/vscode-go/+/345470) contributes a view to the testing pane that lists captured profiles:

![image](https://user-images.githubusercontent.com/879055/132079035-5d4bfa3f-198e-4b58-8198-677201c920b1.png)

Currently, the view does not include any information about what package or module a test is in. Clicking on a test shows the test (opens the containing document and scrolls to the appropriate line). Clicking on a profile opens that profile (currently text only).

**Comment by firelizzard18** [comment]
@hyangah VSCode insiders has support for tagging tests and run profiles microsoft/vscode#129456. If a test is tagged, that test can only be run by run profiles that also have that tag. Tests can have multiple tags, run profiles can only have one tag. Now that running subtests works, I don't think we have any use for tags.

Originally, I planned to use this to improve the UX around running subtests - it would remove the option to run them at all, instead of trying to run them and then seeing an error message. But that's not relevant any more. We could also use this to handle build tags, but once the document symbol provider is switched to gopls, that will be moot. Once gopls has better support for build tags, this could be more relevant.

**Comment by firelizzard18** [comment]
For my own issue tracking:
- Add gopls support for detecting (simple) table-drive tests - #2445
- Add gopls support for including the table entry range in the command response and vscode-go support for running that - #1602
- Add some mechanism for the user to specify which subtest to run, by name - #1734

**Comment by firelizzard18** [comment]
Remaining items are or should be tracked separately
