### ISSUE TITLE
Project repo restructuring

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#3122]
VS Code Go extension will install a new helper go binary (https://github.com/golang/vscode-go/issues/3121) for VS Code Go extension specific tasks. Its source code is in [github.com/golang/vscode-go](github.com/golang/vscode-go) and colocated with the extension code, and the Go extension installs a specific version with the `go install` command.[^1] The tool must be small and has little extra 3rd party dependencies.

Currently, the vscgo package is in a separate module to avoid pulling in large files (TS/JS and media files) and dependencies of [github.com/golang/vscode-go](github.com/golang/vscode-go) repo that are not needed by vscgo.
 
![Screenshot 2024-01-10 at 12 15 18 AM](https://github.com/golang/vscode-go/assets/4999471/613c8551-1557-442c-9ff6-0f069f45bbfd)

Two modules should be released together but require separate tags. For example, the release process for v0.41.0 in the current layout involves:

1. Tag `vscgo/v0.41.0`
  * Extension 0.41.0 runs `go install vscgo@v0.41.0`
  * This tagging must be done before the other tagging.
1. Tag v0.41.0
  * Triggers CI for publishing
  * Serves as the extension version tag
  * Watched by downstream

Given that tagging is a manual process, requiring two tags for every release and prerelease will be tedious and more error prone. And, the [github.com/golang/vscode-go](github.com/golang/vscode-go) module is not actually a Go module meant for publishing.

We propose to move the extension code to a separate module in a subdirectory, and move the vscgo package to [github.com/golang/vscode-go](github.com/golang/vscode-go). That will allow us to require one version tag for extension release.

![Screenshot 2024-01-10 at 12 16 33 AM](https://github.com/golang/vscode-go/assets/4999471/4d8c00c8-7fcb-46c7-9048-1cbd81814caf)

The single tag serves both for vscgo and the extension.

The <code>extension</code> module references the <a href="github.com/golang/vscode-go">github.com/golang/vscode-go</a> module, and it is replaced. This module is meant for local development, so use of this replace directive and invalid version will prevent unexpected dependency on this module, too.

The <code>docs</code> module is a module that contains documentation files, and will include supporting tools.

The build directory remains in the top level for now, but can be punched to a separate module when it grows big. 

### Risk
*   Will affect contributors with pending changes. Good, but sad news - there are not many contributors with pending changes. 
*   NPM scripts should run from the extension directory, which will confuse users. Good contributor guidelines will mitigate confusion.

### Tasks

- [ ] Move code (draft [cl 554316](https://go-review.git.corp.google.com/c/vscode-go/+/554316)) 
  *   Move the extension code to extension/ directory
  *   Adjust build scripts and configuration to work with this new setup
  *   [github.com/golang/vscode-go/go.mod](https://go-review.git.corp.google.com/c/vscode-go/+/554316/6/go.mod)
  *   [github.com/golang/vscode-go/extension/go.mod](https://go-review.git.corp.google.com/c/vscode-go/+/554316/6/extension/go.mod)
  *   The replace directive allows testing and dev extension to build vscgo from the source. (See https://github.com/golang/vscode-go/issues/3121)
- [ ] Update the contributor guideline
- [ ] Update (internal) release process

[^1]:
     That means the tool source code can be fetched from Go module proxies and the source code and its dependencies can be verified with sum.golang.org.
