### ISSUE TITLE
Rebuild test subsystems

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#3523]
# Go Companion

[Go Companion][marketplace] provides an alternative test explorer implementation that uses gopls to discover tests and addresses multiple issues with my original test explorer implementation (which is what vscode-go uses currently).

If you wish to use Go Companion's test explorer, you must:
- Upgrade gopls. Either install from source or wait for v0.17 to be released.
- Install the [Go Companion][marketplace] extension.
- Disable the old implementation by setting `"go.testExplorer.enable": false`.

[marketplace]: https://marketplace.visualstudio.com/items?itemName=ethan-reesor.exp-vscode-go

---

I created this issue to track my work on rebuilding the test explorer and other test subsystems. This work will be done [in a separate repository](https://github.com/firelizzard18/exp-vscode-go) until it is sufficiently complete to merge.

### Goals

* Move test discovery out of the extension into [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls).
* Improve code quality and robustness of VSCode's Testing API/provider.
* Unify all test support into a single system.

### Non-goals

* Sophisticated subtest discovery. Test and subtest discovery will be handled by gopls instead of the extension, so no further work on the extension will be needed (barring unforeseen issues). Improvements to gopls's subtest discovery will be available as soon as they are released and the user updates gopls.

### Tasks

* [x] [Implement `gopls.modules` command](https://go-review.googlesource.com/c/tools/+/598815)
* [x] [Implement `gopls.packages` command](https://go-review.googlesource.com/c/tools/+/600355)
* [x] [Add test discovery to `gopls.packages`](https://go-review.googlesource.com/c/tools/+/548675)
* [x] Implement VSCode's Testing API using gopls for discovery.
* [x] Implement legacy code lenses.
* [x] Improved configurability
  * [x] Include files in the tree.
  * [x] Enable nesting of packages.
  * [x] Disable nesting of subtests.
  * [x] Disable automatic discovery of tests.
* [x] Debug multiple tests (within the same package).
* [x] Support profiling tests/benchmarks.

### Nice to have

* [x] Support continuous runs (https://github.com/golang/vscode-go/issues/1952, https://github.com/golang/vscode-go/issues/2483)
* [x] Support `files.exclude` (https://github.com/golang/vscode-go/issues/1739)
* [x] Add support for test coverage (https://github.com/golang/vscode-go/issues/3331)
* [ ] Support build tags (https://github.com/golang/vscode-go/issues/1673)
* [ ] Address the [backlog of testing issues](https://github.com/orgs/golang/projects/35/views/1).

**Comment by firelizzard18** [comment]
@hyangah VSCode has commands for running tests at the cursor:

<img width="544" alt="image" src="https://github.com/user-attachments/assets/fbfaf9a8-61ca-4ea9-a762-b7e69b67c26b">

And also commands for rerunning the last test run:

<img width="546" alt="image" src="https://github.com/user-attachments/assets/af608868-2fcd-4311-b952-bc59e5a57bf3">

It seems like a number of vscode-go's test commands could be deprecated. Maybe for the time being we replace them with calls to the vscode command and show a deprecation notification? WDYT?

**Comment by firelizzard18** [comment]
I think this issue has served its purpose so I'm going to close it.

For future readers: once gopls v0.17 is prereleased and [CL 613695](https://go-review.googlesource.com/c/vscode-go/+/613695) is merged, you can install [Go Companion](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.exp-vscode-go) and vscode-go will automatically switch to the new implementation. Or you can install a bleeding edge version of gopls, install Go Companion, and manually disable vscode-go's test implementation.
